<a href="https://colab.research.google.com/github/heidimag/DS1000/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2

What are we covering in this lab?
1. Dictionaries
2. Installing and importing Packages
3. Numpy array
4. Pandas DataFrame

## Data Structures

### Dictionaries
https://www.w3schools.com/python/python_dictionaries.asp

Dictionaries are similar to lists. However, it is not indexed by a sequence of numbers but indexed based on `keys`. In practice, it consists of a `key` with an associated `value`. To create a dictionary we use `{key:value}`, when we have more than one key in a dictionary we use `,` to separete the elements of our dictionary.

In [13]:
# Create a dictionary with one key and value
dict_1 = {"Food" : "Happy"}
print(dict_1)

{'Food': 'Happy'}


In [14]:
# Create a dictionary with more than one key
dict_2 = {"a": "alpha", "b": "beta", "g": "gamma"}
print(dict_2)

{'a': 'alpha', 'b': 'beta', 'g': 'gamma'}


We can also have keys with multiple values in a dictionary. In case a key has multiple values, we write them inside `[]` separated by `,`. Later in this lab we are going to use this feature to create Dataframes in Python.

In [15]:
# Create a list with two keys, labeled as Name and Age. Each key has two values.
dict_3 = {"Name": ["Amanda", "Joseph"], "Age": [20, 23]}
print(dict_3)

{'Name': ['Amanda', 'Joseph'], 'Age': [20, 23]}


#### Selecting elements in a dictionary

To select an element in a dictionary, we write the name of our dictionary and inside `[]` we put the key correspoding to the element, that is `name_dictionary["key"]`. Here we use `"key"`since our keys were created as strings, but if we create a key as an integer we don't need to use `""`. Let's practice with some examples.

In [16]:
# Print the value stored in the key = "a" in dict_2
print(dict_2["a"])

alpha


In [20]:
# Create a list in which the keys are represented by integers and select the element corresponding to the key 0
dict_4 = {0 : "Female", 1: "Male"}
print(dict_4[0])

Male


#### Adding new keys and values to an existing dictionary

To add new keys and values to a dictionary we can use the `update` **method** available for dictionaries. To use it, we write `name of dictionary.update(new_dictionary)`. The new dictionary have the keys and values we want to add to our existing dictionary. Let's see an example.

In [23]:
# Create a new dictionary with keys and values we want to add to our dict_3
new_dict = {"Ocupation": ["Student", "Data Scientist"]}

# Adding new_dict to dict_3
dict_3.update(new_dict)

#Print dict_3 to see the change
print(dict_3)

{'Name': ['Amanda', 'Joseph'], 'Age': [20, 23], 'Ocupation': ['Student', 'Data Scientist']}


## Packages


You can think of packages as a directory of Python scripts. Each such script is a so-called module. These modules specify functions, methods and new Python types aimed at solving particular problems. There are thousands of Python packages available from the internet. Among them are packages for data science: there's NumPy to efficiently work with arrays and compute statistics, Matplotlib for data visualization, and Pandas to work with Dataframes.

To use Python packages, you'll first have to `install` them on your own system, and then put code in your script to tell Python that you want to use these packages.

**Pandas:** https://pandas.pydata.org/docs/ <br/>
**Numpy:** https://numpy.org/doc/1.20/user/absolute_beginners.html

### Numpy package

#### Installing packages

Installing packages in Python is not difficult, we need to use `pip install` `package_name`

In [ ]:
pip install numpy

#### Importing packages

Now, that we have installed numpy package we can import it using `import` `package_name`. Sometimes the package's name is too long so we can create a nickname for it using `as` `nickname` when importanting the package. So everytime we want to use the package we can called it by its nickname.

In [29]:
# Import package numpy with nickname np
import numpy as np

#### Arrays

**np.array**: https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [ ]:
# Get error when we don't specified the package the function array is from
array([1,2,3,4])

To use function from packages we need to specify the package before running the function as `package's_name_or_nickname.function()`

In [ ]:
np.array([1,2,3,4])

In [39]:
# Create  2D arrays
arr_1 = np.array([[1, 2], [3, 2]])
arr_2 = np.array([[5, 4], [6, 7]])
print(arr_1)
print(arr_2)

[[1 2]
 [3 2]]
[[5 4]
 [6 7]]


In [38]:
# Print shape of an array. Shape = (number of rows, number of columns)
print("Shape of arr_1:", np.shape(arr_1))
print("Shape of arr_2:", np.shape(arr_2))

Shape of arr_1: (2, 2)
Shape of arr_2: (2, 2)


In [34]:
# Array operators
print("dot product:\n", arr_1 @ arr_2)

dot product:
 [[17 18]
 [27 26]]


In [35]:
# Elementwise exponential
print("exponents:\n", arr_1 ** 2)

exponents:
 [[1 4]
 [9 4]]


In [36]:
# Elementwise multiplication
print("scalars\n", arr_1 * 5)

scalars
 [[ 5 10]
 [15 10]]


In [37]:
# Create an array filled of ones of given shape (3,3)
print("Array with entries of 1: \n", np.ones((3, 3)))

Array with entries of 1: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Create an array filled of zeros of given shape (2,1)
print("Array with entries of 0: \n", np.zeros((5, 1)))

In [ ]:
# Evenly spaced numbers over a specified interval (start, end, number of values you want in the interval)
print("Sequence:\n", np.linspace(2, 9, 3))

In [ ]:
# Sort in an ascending order an array by row
print("Sorted arr_1:\n", np.sort(arr_1))

#### Pandas package

#### Install pandas package

In [ ]:
# We need to install a package once, then you comment (#) the next line of code

In [ ]:
pip install pandas

#### Importing pandas package

In [43]:
import pandas as pd

### Creating DataFrames in Python

**pd.DataFrame:** https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

To create DataFrames (Tables) in Python we use the method `DataFrame` available in the Pandas package. In this course, if you want to create a DataFrame from scratch, we first create a dictionary with keys as the columns of our table. Then, we use `pd.DataFrame(dictionary_name)` to transform our dictionary into a DataFrame into Python. Let's see an example

In [44]:
df_data = {"Age" : [1, 2], "Height" : [5, 10]}
df = pd.DataFrame(data = df_data)
df

Age  Height
0    1       5
1    2      10

#### Getting the shape of a DataFrame

We can use the `shape` method to get the number of rows and columns in a DataFrame. Recipe: `name_dataframe.shape`

In [46]:
df.shape

(2, 3)

#### Adding a new column to a DataFrame

Image we want a new column to our DataFrame `df`. We know that `df` has 2 rows (observations) and 2 columns (variables) so our new columns need to have two rows as well.

In [45]:
df["Weight"] = [10, 25]
df

Age  Height  Weight
0    1       5      10
1    2      10      25

#### Selecting columns by name

If you want to select a column in a DataFrame, per example, to see the obervations for that column, you can use the `"column_name"` inside `[]` to select the column. Then, we use the `print` function to display the result.

In [48]:
print(df["Height"])

0     5
1    10
Name: Height, dtype: int64


Another way to select columns by name is to use `.loc[,]` method, we can select more than one column using this method.

To select a column we use `.loc[:, "name_column"]`, `:` means that we want all rows (observations) for that column.

In [47]:
#Select Column Age
df.loc[: , "Age"]

0    1
1    2
Name: Age, dtype: int64

**Practice:** Select all observations for Column `'Weight'` in DataFrame `df` using the `loc` method

In [49]:
# your code here
df.loc[:, "Weight"]

0    10
1    25
Name: Weight, dtype: int64

#### Selecting rows or columns by index
We can also select rows and columns by their index. **Remember** Python stars the index from 0. So, if you want to select the `Age` column since it is the first column in our DataFrame we need to use `0` to select it.

Also, to select rows or columns by index we need to use one `.iloc[rows,columns]` where `.iloc[:,1]` means that we want all observations for the second column and `.iloc[0,:]` means that we want all columns values for the first observation.

In [51]:
# Selecting all observations for the first column using the index of the column
df.iloc[:,0]

0    1
1    2
Name: Age, dtype: int64

In [ ]:
# Selecting only the first element (index 0) of the third column (index 2)
df.iloc[0,2]

In [ ]:
# Showing the whole dataframe
df.iloc[:]

#### Selecting elements by their values

If you want to select all the information for the row (observation) that has 'Age' equals to 2, we can use the comparison operators from the previous Lab to do that

In [ ]:
# Selecting the whole row where 'Age' is equals to two.
df[df["Age"] == 2]

In [ ]:
# Select only the information of the column Height when the observations have 'Age' smaller than two
df["Height"][df["Age"] < 2]

We can also extract a column using `df_name.column_name` instead of `df['column_name']` like we did previously.

In [ ]:
# Selecting the whole row where 'Height' is equals to 10.
df[df.Height == 10]

**Practice:** Create a DataFrame called `data` with columns named `'A'`, `'B'` and `'C'`. `'A'` has values 'John', 'Camile', 'Matilda'. `'B'` has values 2, 10, 25 and `'C'` has values 0, 0, 1. Then called `data` to display the DataFrame.

Hint: You need to create a dictionary first with keys `'A'`, `'B'`, and `'C'`, and value `['John', 'Camile', 'Matilda']`, `[2, 10, 25]` and `[0, 0, 1]`.

Go back and check how to create a dictionary in the beginning of this Lab and then recall how we created our first DataFrame (Go back to the section **Creating DataFrames in Python to remember**)

In [55]:
#your code here
import pandas as pd
data = {'A':['John','Camile','Matilda'],'B':[2,10,25],'C':[0,0,1]}
data = pd.DataFrame(data)
data

A   B  C
0     John   2  0
1   Camile  10  0
2  Matilda  25  1